### ISSUE TITLE
Exception when running multiple tests

### ISSUE THREAD

**Issue by charlesfayal** [connelhooley/AkkaTestingHelpers#3]
When I run tests individually they run fine. When I run multiple all but one fails. 
Using NUnit 

`  Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
    TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    <>c.<InitializeTest>b__10_1(Config c)
    Option`1.Select[TNew](Func`2 selector)
    TestKitBase.InitializeTest(ActorSystem system, ActorSystemSetup config, String actorSystemName, String testActorName)
    TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName)
    TestKit.InitializeActorSystemOnSetUp()
    --TearDown
    TestKitBase.Dilated(TimeSpan duration)
    TestKitBase.Shutdown(ActorSystem system, Nullable`1 duration, Boolean verifySystemShutdown)
    TestKitBase.Shutdown(Nullable`1 duration, Boolean verifySystemShutdown)
    TestKit.AfterAll()
    TestKit.ShutDownActorSystemOnTearDown()
`

**Comment by connelhooley** [comment]
Hi Charles

That doesn't really give me a lot to go with. What do the tests look like, are you doing anything in the tear down method?

I personally always use XUnit instead of NUnit for Akka tests. This is because in NUnit tests inside the same class share the same `ActorSystem`. In Xunit each test gets its own `ActorSystem` so you get better isolation. Are you in a position where you could try XUnit instead?

**Comment by connelhooley** [comment]
Closing due to lack of information.
